# Generated by Django 4.2.16 on 2024-11-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fooditem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('non_veg', models.BooleanField(default=False)),
            ],
        ),
    ]
