# Generated by Django 4.2.16 on 2024-11-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodieBay', '0002_fooditem_image_alter_fooditem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
